server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/LarussoAuto
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true